In [1]:
import torch 
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_ones= torch.ones_like(x_data)

In [4]:
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [5]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [7]:
x_rand= torch.rand_like(x_data,dtype=torch.float)

In [8]:
x_rand

tensor([[0.1879, 0.7977],
        [0.0508, 0.9841]])

In [10]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

In [11]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

In [14]:
torch.cuda.is_available()

False

In [15]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\MSADEGH/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100%|██████████████████████████████████████████████████████████████████████████████| 44.7M/44.7M [01:03<00:00, 738kB/s]


In [16]:
prediction = model(data)

In [17]:
loss = (prediction - labels).sum()

In [18]:
loss.backward()

In [19]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)


In [20]:
optim.step() 

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device
